site_name: Zooli Documentation
site_url: https://docs.zooli.io/
theme:
  name: material
  logo: docs/assets/zws_logo_square_white.png
  favicon: docs/assets/favicon.png
font:
  text: DM Sans
  code: Roboto Mono
palette: 
  primary: custom
  accent: custom
extra_css: 
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-3BF57DHM3R
